export var locations =
["Broadway Theater",
"Casino",
"Circus Tent",
"Corporate Party",
"Movie Studio",
"Bank",
"Day Spa",
"Hotel",
"Restaurant",
"Supermarket",
"Service Station",
"Hospital",
"Embassy",
"Military Base",
"Police Station",
"School",
"University",
"Airplane",
"Ocean Liner",
"Passenger Train",
"Pirate Ship",
"Submarine",
"Cathedral",
"Crusader Army",
"Polar Station",
"Space Station"]
